#!/usr/bin/python

import os
import time,re

codes = {
100:"Continue",
200:"OK",
202:"Accepted",
204:"No Content",
301:"Moved Permanently",
400:"Bad Request",
401:"Unauthorized",
403:"Forbidden",
404:"Not Found",
405:"Method Not Allowed",
406:"Not Acceptable",
408:"Request Timeout",
415:"Unsupported Media Type",
500:"Internal Server Error",
501:"Not Implemented",
503:"Service Unavailable",
505:"HTTP Version Not Supported"
}

types = {
".gif":"image/gif",
".jpeg":"image/jpeg",
".jpg":"image/jpeg",
".png":"image/png",
".tiff":"image/tiff",
".tff":"image/tiff",
".txt":"text/plain",
".log":"text/plain",
".htm":"text/html",
".html":"text/html",
".py":"text/plain"
}

#accepts time in seconds since the epoch, returns date in rfc822
def httpdate(rtime):
	return time.strftime("%a, %d %b %Y %H:%M:%S GMT", time.gmtime(rtime))

#accepts filename, returns mime type based on extention, or
#application/octet-stream if type cannot be determined
def gettype(rpath):
	ext = os.path.splitext(rpath)[1]
	try:
		return types[ext]
	except KeyError:
		return 'application/octet-stream'
		
#accepts url, returns url with all the % characters decoded into ascii
escapeSeq = re.compile(r"%(..)")
def urlDecode(url):
	def unescaper(match):
		return chr( int(match.group(1),16) )
	
	return escapeSeq.sub(unescaper,url)

def parseQuery(query):
	pairs = query.split('&')
	query = dict()
	for pair in pairs:
		try:
			key,value = pair.split('=')
		except ValueError:
			continue
		query[key] = value
	
	return query
		
def parseListing(listing,path,key):
	lines = list()
	for file in listing:
		if file[0] == '.': continue
		
		filepath = os.path.join(path,file)
		stats = os.stat(filepath)
		
		line = [file]
		line.append(stats.st_mtime)
		if os.path.isdir(filepath):
			line.append(None)
		else:
			line.append(stats.st_size)
		lines.append(line)
	
	#sort using the schwartizan transform
	#decorate:
	dec = [(line[key],line) for line in lines]
	#sort
	dec.sort()
	#undecorate
	lines = [line for d,line in dec]

	return lines

	
def genIndex(path,params,url):
	key = 0
	reverse = False
	reversing = [0,0,0]

	if params:
		query = parseQuery(params)
		try:
			key = int(query['key'])
		except KeyError:
			pass
		try:
			reverse = bool(query['reverse'])
		except KeyError:
			pass
	
	listing = os.listdir(path)
	listing = parseListing(listing,path,key)
	if reverse:
		listing.reverse()
	else:
		reversing[key] = 1

	#format the fields like they'll be displayed
	postfixes = ['','KB','MB','GB','TB','PB','EB','ZB','YB']
	for line in listing:
		line[1] = httpdate(line[1]) #convert date to http format
		
		if line[2] == None:		# if it was a directory, 
			line[0] += '/'			#append /
			line[2] = '-'			#replace size with '-'
		elif line[2] < 1024:	# if size is less then 1K
			line[2] = str(line[2])	#just convert it to a string
		else:					# otherwise
			postfix = 0
			size = float(line[2])	#format size properly
			while size > 1024:
				size /= 1024
				postfix += 1
			line[2] = "%.1f%s" % (size,postfixes[postfix])
	
	title = "Index of " + url
	page = ('<html>\n\t<head><title>%s</title></head>\n\
	\t<body>\n\t\t<h1>%s</h1>\n\
	<pre><a href="?key=0&reverse=%d">Name</a>' + ' '*36 + 
	'<a href="?key=1&reverse=%d">Last Modified</a>\t\t\t<a href="?key=2&reverse=%d">Size</a><hr>') % (
							title,title,reversing[0],reversing[1],reversing[2])
	for line in listing:
		page += ("""<a href="%s">%s</a>""" + ' '*(40-len(line[0])) + 
				"""%s\t%s\n""") % (line[0],line[0],line[1],line[2])
	
	page += "<hr></pre></body></html"
	return page

def runCgi(request):
	entity = "Content-type: text/plain\r\n\r\n"
	entity += "this was generated by cgi!\n\n"
	entity += str(request)
	return entity
